baseURL = "http://localhost"
copyright = "© 2020 - 2023 Dilanka Kaushal Hewage"
title = "Dilanka Kaushal Hewage"
#paginate = 10
enableRobotsTXT = true
enableGitInfo = true

[build]
  noJSConfigInAssets = true
  [build.buildStats]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
  quality = 90

[outputs]
  home = ["html", "rss", "searchIndex"]

[outputFormats]
  [outputFormats.searchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true

[params]
  # Set default theme to dark (Dracula is a dark theme)
  defaultTheme = "dark"
  # Dracula's primary color is purple, but you can adjust as needed
  themeColor = "purple"
  # Dracula typically has high contrast
  themeContrast = "hard"
  author = "Dilanka Kaushal Hewage"
  subtitle = "Red Team / Offensive Security Engineer"
  description = "Gray Hat"

  # Plausible auth secret to enable public dashboard
  plausibleAuth = "hDl_ZT_txy4BS608-H3Y0"

  [params.logo]
    text = "n3rdh4x0r.blog"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "csharp",
      "hcl",
      "ignore",
      "json",
      "markdown",
      "powershell",
      "toml",
      "yaml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "command-line"
    ]

  # Social share links for posts
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "x"
    formatString = "https://x.com/intent/post?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "linkedin"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "ycombinator"
    formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    iconSuite = "tabler-icon"
    iconName = "mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 20
  #[[menu.main]]
  #  identifier = "cv"
  #  name = "CV"
  #  url = "/cv"
  #  weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40
  [[menu.main]]
    identifier = "stats"
    name = "Stats"
    url = "/stats"
    weight = 50

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
  [languages.de]
    languageName = "Deutsch"
    weight = 20
    [languages.de.params.jsonResume]
      present = "heute"
